### ISSUE TITLE
Rouge-L 

### ISSUE THREAD

**Issue by 320834** [ananddtyagi/AJ-summarization#3]
Uses longest common sub sequence to determine the similarity between two documents.

**Comment by ananddtyagi** [comment]
Using longest common sub-seq may not be the best for what we are doing here. For the extractive, if it's the wrong sentence, then the longest common subsequence would be the sentence anyway. For abstractive, we need to find a way to see how similar the sentences are in general. I think a total-matching-words or cos sim using embeddings may allow us to get a better sense of if the two outputs are related or not.
